### ISSUE TITLE
Роутер для фреймов

### ISSUE THREAD

**Issue by iamsalnikov** [liverecord/lrs#4]
Я поизучал то, как сейчас реализована обработка сообщений (фреймов), которые поступают из вебсокета. Заметил несколько спорных моментов:

1. AppContext занимается как хранением контекста, так и обработкой фреймов. Не слишком ли большая ответственность у него? Не грозит ли это в будущем превращением в "Божественный объект"?
2. При росте количества типов фреймов будет разрастаться свитч.

Что хочу предложить.

Я хочу предложить реализовать роутер для фреймов примерно по следующей схеме:

1. Определяем схему для хандлера

```go
type HandlerFunc func(ctx *AppContext, data string) error
```

Каждый хандлер принимает контекст, в котором лежит сейчас все то, что и лежит в текущей реализации. 

2. Делаем роутер со следующим интерфейсом:

```go
type WSRouter interface {
	RegisterHandler(route string, handler HandlerFunc)
        DefaultRoute(route string) // возможно, лишнее
	Handle(ctx *AppContext, route string) error
}
```

3. В начале работы приложения регистрируем все обработчики.

4. Обработка сообщения выглядит примерно следующим образом:

```go
err := router.Handle(lr, frame.Type)
if err != nil {
        // process error
}
```

Таким  образом, мы получаем организацию, где контекст занимается хранением контекста, с него снимается ответственность за обработку сообщений. Выделяем отдельную схему для обработчиков сообщений, которые мы можем группировать как душе угодно, и не заниматься расширением AppContext. Получаем отдельный компонент, который занимается строго отведенной задачей - маршрутизацией фреймов. Выходит, что контекст сам по себе, маршрутизация сама по себе, обработка сообщений также в стороне. Все занимаются четко определенной работой и не происходит смешения ответственностей.

Также, если уж на то пошло, я хотел бы предложить убрать из контекста приложения Ws. Объясню почему. Мне кажется, что WS относится не к контексту приложения, а к контексту запроса. Отчего, я бы схему хандлера изменил бы вообще следующим образом:

```go
type HandlerFunc func(ctx *AppContext, ws *websocket.Conn, data string) error
```
Либо еще вариант: хандлер сам не занимается отправкой сообщения. Он занимается лишь его формированием. А высылается оно уже на другом уровне. Тут уже дело вкуса.

Это черновой вариант интерфейсов. Критика и предложения приветствуются. Если ты не против этой инициативы, то я бы взял эту задачу на себя.

**Comment by iamsalnikov** [comment]
Приведу примерный псеводокод того, как бы это все могло работать:

```go

var wsRouter *WSRouter

func PingHandler(ctx *AppContext, ws *websocket.Conn, data string) error {
	ws.WriteJSON(Frame{
		Type: PingFrame,
		Data: "Pong",
	})

	return nil
}

func handleConnections() {
	//....

	for {
		frame := someBuildFrameFunc()
		
		// Тут внутри поиск нужного обработчика и его вызов: handler(lr, ws, data)
		wsRouter.Handle(lr, ws, frame.Type, frame.Data)
		
	}
}

func main() {
	// init app ...

	wsRouter = &WSRouter{}
	wsRouter.RegisterHandler(PingFrame, PingHandler)

	// another setup...

}
```

**Comment by zoonman** [comment]
Контекст в первую очередь нужен для того, чтобы идентифицировать пользователя после аутентификации. 
Я пока не разобрался с Go до конца. У меня была идея немного другого характера - автоматический поиск обработчика.
Что-то типа `handlers.(frame.Type)(frame)`. Я еще не настолько хорошо знаю язык.

**Comment by iamsalnikov** [comment]
> Контекст в первую очередь нужен для того, чтобы идентифицировать пользователя после аутентификации

Да, примерно об этом я и писал. Что в текущей реализации у контекста очень большая ответственность. Он же и контекст, он же и обработчик всех запросов.

> Что-то типа handlers.(frame.Type)(frame). Я еще не настолько хорошо знаю язык.

Ну, вот поиском обработчика запроса и должен заниматься роутер, имхо. К нему пришел запрос - он направил его куда нужно, в соответствии с установленными правилами на этапе инициализации приложения. 

Так мы разделим ответственности и для каждой задачи будет свой инструмент:
1. Хранение контекста приложения - конекст приложения
2. Маршрутизация запросов - роутер
3. Обработка запросов - хандлеры

**Comment by zoonman** [comment]
У меня контекст знает о пользователе и это очень важно. Для каждого пользователя свой контекст. Инстанциирование очень дешевое поскольку он несет только указатели.

**Comment by zoonman** [comment]
Мне язык надо немного подучить, я очень многое еще не знаю или не понимаю, как работает.
